@startuml "Applying a profile"

note left
    EnumWindows callback called.
end note

(*) --> if "Profile is loaded?" then
    if "Profile specifies title?" then
        -->[true] "Get HWND title"
        if "Profile title == HWND title" then
            -->[true] "Apply profile properties"
            --> (*)
        else
            -->[false] (*)
        endif
    else
        if "Profile specifies process?" then
            -->[true] "Get HWND process"
            if "Profile process == HWND process" then
                -->[true] "Apply profile properties"
                --> (*)
            else
                -->[false] (*)
            endif
        else
            -->[false] (*)
        endif
    endif
else
    -->[false] (*)
endif

@enduml